name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build documentation
      run: |
        # Create docs directory if it doesn't exist
        mkdir -p docs
        
        # Copy any additional assets
        cp -r docs/* docs/ 2>/dev/null || true
        
        # Create a simple index.html if it doesn't exist
        if [ ! -f docs/index.html ]; then
          echo "Creating basic documentation..."
        fi
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        cname: flow-engine.github.io
        
    - name: Deploy to GitHub Pages (Alternative)
      uses: actions/deploy-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        artifact_name: github-pages
        path: ./docs
